# Generated by Django 4.2.16 on 2024-11-23 01:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='errors',
            field=models.ManyToManyField(blank=True, to='errors.error'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='error_log',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
