# Generated by Django 4.2.16 on 2024-11-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_userproject_errors_userproject_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='project_file',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
