# Generated by Django 4.2.16 on 2024-11-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_userproject_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='error_resolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
