# Generated by Django 4.2.16 on 2024-11-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_userproject_error_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('project_description', models.TextField(verbose_name='Description')),
                ('error_resolution', models.TextField(blank=True, null=True, verbose_name='Error Resolution')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Uploaded File')),
            ],
        ),
        migrations.AlterField(
            model_name='userproject',
            name='error_resolution',
            field=models.TextField(blank=True, null=True, verbose_name='Error Resolution'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='project_description',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userproject',
            name='project_name',
            field=models.CharField(max_length=255, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Uploaded File'),
        ),
    ]
