# Generated by Django 4.2.16 on 2024-11-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_alter_userproject_error_resolution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('solution', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='error_log',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='project_file',
        ),
        migrations.AlterField(
            model_name='userproject',
            name='errors',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.error'),
        ),
    ]
