# Generated by Django 4.2.16 on 2024-11-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_error_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='errors',
        ),
        migrations.AlterField(
            model_name='userproject',
            name='project_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.DeleteModel(
            name='Error',
        ),
        migrations.AddField(
            model_name='projectdescription',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='projects.userproject'),
        ),
    ]
