# Generated by Django 4.2.16 on 2024-11-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0005_alter_error_solution'),
        ('projects', '0008_projectdescription_delete_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='errors',
            field=models.ManyToManyField(blank=True, related_name='projects', to='errors.error'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='project_description',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
