# Generated by Django 4.2.16 on 2024-11-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0002_alter_error_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='error',
            name='description',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='error',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='error',
            name='solution',
            field=models.TextField(verbose_name='解決方法'),
        ),
        migrations.AlterField(
            model_name='error',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
