# Generated by Django 4.2.16 on 2024-11-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0004_alter_error_created_at_alter_error_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='solution',
            field=models.TextField(verbose_name='解決方法'),
        ),
    ]
